variable "generated_key_name" {
    type        = string
    default     = "terraform-key-pair"
    description = "Key-pair generated by Terraform"
}

variable "pm_api_url" {
    type        = string
    description = "Proxmox API URL"
}

variable "node" {
    type        = string
    default     = "node"
    description = "Proxmox node"
}

variable "hostname" {
    type        = string
    default     = "terraform-deploy"
    description = "Hostname of the LXC container"
}

variable "ostemplate" {
    type        = string
    default     = "local:vztmpl/ubuntu-20.04-standard_20.04-1_amd64.tar.gz"
    description = "OSTemplate to use for the LXC container"
}

variable "pool_name" {
    type        = string
    default     = "CT"
    description = "Pool to use for the LXC container"  
}

variable "unprivileged" {
    type        = bool
    default     = false
    description = "Create an unprivileged LXC container"
}

variable "memory" {
    type        = string
    default     = "1024"
    description = "Memory to allocate to the LXC container"
}

variable "cores" {
    type        = string
    default     = "2"
    description = "Number of cores to allocate to the LXC container"
}

variable "start" {
    type        = bool
    default     = true
    description = "Start the LXC container after creation"
}

variable "storage" {
    type        = string
    default     = "local"
    description = "Storage to use for the LXC container"
}

variable "storage_size" {
    type        = string
    default     = "8G"
    description = "Size of the rootfs for the LXC container"
}

variable "nic_name" {
    type        = string
    default     = "eth0"
    description = "Name of the network interface"
}

variable "bridge_name" {
    type        = string
    default     = "vmbr0"
    description = "Bridge to use for the network interface"
}

variable "gateway_address" {
    type        = string
    default     = "192.168.1.1"
    description = "Gateway address for the network interface"
}

variable "ipv4_address" {
    type        = string
    description = "value of the ipv4 address for the network interface"
}

variable "firewall" {
    type        = bool
    default     = true
    description = "Enable firewall for the LXC container"
}